### ISSUE TITLE
删除请求：请求撤销 d1170ca99950944d00362893e8c8b3dbaff101b3 提交带来的变更

### ISSUE THREAD

**Issue by Candinya** [TechOtakupoi233/TwitterHub#6]
因为我现在已经不再使用 PhotoShop 了所以请恕我无法直接开启 PR 
申请撤销 d1170ca99950944d00362893e8c8b3dbaff101b3 该次提交（及可能存在的后续变更）带来的影响
针对本人账户（Nya Candy） 申请清理涉及的数据
麻烦您了，非常感谢 🙏

**Comment by TechOtakupoi233** [comment]
额，这个项目...已经埋了
由于项目的性质，想删除你的记录的话，恐怕最管用的方法是直接rebase到 9f6111a23b03413eb549d451d5963ec282e69bb5 ，还要删掉2020年后的两个release，还有之前的issue和PR？
如果你确定要这么做的话。

**Comment by Candinya** [comment]
只是清理掉图片就好，记录本身不用在意（涉及到的改动太大了，非代码类管理起来比较麻烦）
（如果方便的话，不方便就不处理也没关系hhhh

**Comment by TechOtakupoi233** [comment]
只需要删掉psd内的数据么？

**Comment by Candinya** [comment]
嗯，足够了，非常感谢 🙏

**Comment by TechOtakupoi233** [comment]
eda36638b95cbc31c2ccbdea1ceb7dcac581f225
